name: 'Post2Discord'
description: 'A GitHub Action to send notifications to a Discord channel via webhook'
author: 'Jeff Patton'

branding:
  icon: 'bell'
  color: 'blue'

inputs:
  message:
    description: 'The message to post to Discord.'
    required: true

secrets:
  discordWebhook:
    description: 'The webhook URL for the Discord channel where notifications will be sent.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Send Discord Notification
      run: |
        pwsh -File post2discord.ps1 -Message "${{ inputs.message }}" -DiscordWebhook "${{ secrets.discordWebhook }}"
      shell: pwsh
