name: 'Post2Discord'
description: 'A GitHub Action to send a notification to a Discord channel via webhook.'
author: 'Jeff Patton'

branding:
  icon: 'bell'
  color: 'blue'

inputs:
  message:
    description: 'The message to post to Discord.'
    required: true
  discordWebhook:
    description: 'The Discord webhook URL to send the notification to.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Send Discord Notification
      run: |
        & $env:GITHUB_ACTION_PATH\\post2discord.ps1 -Message "${{ inputs.message }}" -DiscordWebhook "${{ inputs.discordWebhook }}"
      shell: pwsh
