name: Discord Notification Workflow

on:
  workflow_call:
    inputs:
      source:
        required: true
        type: string
      projectName:
        required: true
        type: string
    secrets:
      discordWebhook:
        required: true

jobs:
  notify_discord:
    runs-on: windows-latest
    name: Send notification to Discord
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send Discord Notification
        env:
          DiscordWebHook: ${{ secrets.discordWebhook }}
          Source: ${{ inputs.source }}
          ProjectName: ${{ inputs.projectName }}
        run: |
          pwsh -File post2discord.ps1 -Source $Source -ProjectName $ProjectName -DiscordWebhook $DiscordWebHook
        shell: pwsh